// ignore_for_file: unused_element, unused_element_parameter, unused_field, unused_local_variable, dead_code, deprecated_member_use, use_super_parameters, prefer_const_constructors, use_build_context_synchronously, duplicate_ignore, avoid_web_libraries_in_flutter, avoid_unnecessary_containers
import 'dart:async';
import 'dart:io';
import 'dart:math';
import 'dart:ui' as ui;

import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:share_plus/share_plus.dart';
import 'package:path_provider/path_provider.dart';
import 'package:cached_network_image/cached_network_image.dart';
import 'package:vision_gallery_saver/vision_gallery_saver.dart';
import 'package:google_fonts/google_fonts.dart';

import '../../utils/collage_generator.dart';
import '../../core/sl_theme.dart';
import '../../services/collage_limit_service.dart';
import '../../services/image_picker_recovery_service.dart';
import '../../utils/services/app_lifecycle_presence_guard.dart';
import 'sticker_library_screen.dart';

part 'collage_maker/panels/collage_intro_panel.dart';
part 'collage_maker/panels/collage_controls_panel.dart';
part 'collage_maker/collage_memory_source_part.dart';
part 'collage_maker/widgets/collage_preview_widgets.dart';
part 'collage_maker/collage_maker_helpers.dart';

const Color _paperCream = Color(0xFFF7F0E6);
const Color _paperShell = Color(0xFFFFF9F2);
const Color _paperRose = Color(0xFFD0A193);
const Color _paperRoseDeep = Color(0xFFA76F61);
const Color _paperMist = Color(0xFFC7D4C8);
const Color _paperMistDeep = Color(0xFF7B988A);
const Color _paperSand = Color(0xFFE7D5BF);
const Color _paperCocoa = Color(0xFF6A4C40);
const Color _paperInk = Color(0xFF463730);
const Color _paperMuted = Color(0xFF8E766B);
const Color _paperLine = Color(0xFFD9C7B8);

class CollageMakerScreen extends StatefulWidget {
  final String houseId;
  const CollageMakerScreen({super.key, required this.houseId});

  @override
  State<CollageMakerScreen> createState() => _CollageMakerScreenState();
}

class _EditableCollagePhoto {
  final String source;
  double scale;
  Offset offset;

  _EditableCollagePhoto({
    required this.source,
    this.scale = 1,
    this.offset = Offset.zero,
  });

  CollagePhotoTransform get transform => CollagePhotoTransform(
        scale: scale,
        offset: offset,
      );
}

class _FramePinchSession {
  final int index;
  final Offset startOffset;
  final double startScale;

  const _FramePinchSession({
    required this.index,
    required this.startOffset,
    required this.startScale,
  });
}

class _CollageMakerScreenState extends State<CollageMakerScreen> {
  static const int _collageDecodeMaxDimension = 1400;
  static const int _collagePreviewDecodeMaxDimension = 720;
  static const int _imageLoadBatchSize = 4;
  static const Duration _autoGenerateDebounceDuration =
      Duration(milliseconds: 360);
  static const List<_CollageStylePreset> _stylePresets = [
    _CollageStylePreset(
      id: 'grid',
      label: 'Lưới',
      subtitle: 'Cân đều',
      accent: _paperRoseDeep,
      background: Color(0xFFF4E6DE),
    ),
    _CollageStylePreset(
      id: 'masonry',
      label: 'So le',
      subtitle: 'Nhịp lệch',
      accent: Color(0xFFB4895B),
      background: Color(0xFFF7EEDD),
    ),
    _CollageStylePreset(
      id: 'story',
      label: 'Dọc nổi bật',
      subtitle: 'Dọc nổi bật',
      accent: _paperMistDeep,
      background: Color(0xFFEEF3ED),
    ),
    _CollageStylePreset(
      id: 'poster',
      label: 'Ngang tạp chí',
      subtitle: 'Ngang tạp chí',
      accent: Color(0xFF5E7B72),
      background: Color(0xFFE9F0EC),
    ),
    _CollageStylePreset(
      id: 'polaroid',
      label: 'Ảnh giấy',
      subtitle: 'Album giấy',
      accent: _paperCocoa,
      background: Color(0xFFF5E8DB),
    ),
    _CollageStylePreset(
      id: 'scatter',
      label: 'Bay tự do',
      subtitle: 'Bay tự do',
      accent: Color(0xFFC18B73),
      background: Color(0xFFF7EBE3),
    ),
    _CollageStylePreset(
      id: 'heart',
      label: 'Trái tim',
      subtitle: 'Trái tim',
      accent: Color(0xFF9A6F74),
      background: Color(0xFFF2E4E1),
    ),
  ];
  static const List<_CollageAspectPreset> _aspectPresets = [
    _CollageAspectPreset(
      id: '9:16',
      label: '9:16',
      subtitle: 'Story dọc',
      width: 9,
      height: 16,
    ),
    _CollageAspectPreset(
      id: '4:5',
      label: '4:5',
      subtitle: 'Feed dọc',
      width: 4,
      height: 5,
    ),
    _CollageAspectPreset(
      id: '3:4',
      label: '3:4',
      subtitle: 'Khung dọc',
      width: 3,
      height: 4,
    ),
    _CollageAspectPreset(
      id: '1:1',
      label: '1:1',
      subtitle: 'Vuông',
      width: 1,
      height: 1,
    ),
    _CollageAspectPreset(
      id: '4:3',
      label: '4:3',
      subtitle: 'Máy ảnh',
      width: 4,
      height: 3,
    ),
    _CollageAspectPreset(
      id: '3:2',
      label: '3:2',
      subtitle: 'Album ngang',
      width: 3,
      height: 2,
    ),
    _CollageAspectPreset(
      id: '16:9',
      label: '16:9',
      subtitle: 'Màn rộng',
      width: 16,
      height: 9,
    ),
  ];
  static const List<_CollageBackgroundPreset> _backgroundPresets = [
    _CollageBackgroundPreset(
      id: 'default',
      label: 'Mặc định',
      subtitle: 'Nền hiện tại',
      accent: _paperRoseDeep,
      background: Color(0xFFF7F0E6),
      icon: Icons.wallpaper,
    ),
    _CollageBackgroundPreset(
      id: 'cloud_pink',
      label: 'Mây hồng',
      subtitle: 'Pastel ngọt',
      accent: Color(0xFFC98FA1),
      background: Color(0xFFF9E8EE),
      icon: Icons.cloud,
    ),
    _CollageBackgroundPreset(
      id: 'bogo_blue',
      label: 'Bogo xanh',
      subtitle: 'Mây xanh cute',
      accent: Color(0xFF7FA9C8),
      background: Color(0xFFE7F2FA),
      icon: Icons.bubble_chart,
    ),
    _CollageBackgroundPreset(
      id: 'cotton_candy',
      label: 'Kẹo bông',
      subtitle: 'Bồng bềnh sáng',
      accent: Color(0xFFB991D8),
      background: Color(0xFFF4EBFB),
      icon: Icons.auto_awesome,
    ),
  ];

  bool _isFromMemory = true;
  String _selectedStyle = 'grid';
  String _selectedBackgroundTheme = 'default';
  String _selectedAspectRatio = '4:5';
  double _photoScale = 1.0;
  final List<_EditableCollagePhoto> _editablePhotos = [];
  int? _activeEditorIndex;
  int? _hoveredSwapTargetIndex;
  double _previewTileSize = 0;
  _FramePinchSession? _framePinchSession;
  final Set<String> _selectedStickers =
      StickerLibraryScreen.stickers.take(3).toSet();
  static final List<String> _stickerOptions = StickerLibraryScreen.stickers;
  bool _showAllStickerOptions = false;
  final TextEditingController _titleCtrl = TextEditingController();
  bool _isGenerating = false;

  List<Map<String, dynamic>> _memoryPhotos = [];
  List<String> _availableMonths = [];
  String _selectedMonth = 'all';

  final List<XFile> _deviceFiles = [];
  final ImagePicker _picker = ImagePicker();
  final Map<String, ui.Image> _decodedImageCache = {};
  final Set<String> _hiddenMemoryPhotoKeys = <String>{};
  int _generationTicket = 0;
  int _collageLayoutSeed = DateTime.now().microsecondsSinceEpoch & 0x7fffffff;
  Timer? _autoGenerateDebounceTimer;
  String? _queuedAutoGenerationFingerprint;
  String? _lastCompletedAutoGenerationFingerprint;
  bool _hasFullQualityRender = false;

  Uint8List? _generatedCollageBytes;

  @override
  void initState() {
    super.initState();
    _fetchMemoryPhotos();
  }

  @override
  void dispose() {
    _autoGenerateDebounceTimer?.cancel();
    _generationTicket++;
    for (final image in _decodedImageCache.values) {
      try {
        image.dispose();
      } catch (_) {}
    }
    _titleCtrl.dispose();
    super.dispose();
  }

  List<_EditableCollagePhoto> _syncEditablePhotos(List<String> urls) {
    final existingBySource = <String, List<_EditableCollagePhoto>>{};
    for (final item in _editablePhotos) {
      existingBySource.putIfAbsent(item.source, () => []).add(item);
    }

    _editablePhotos
      ..clear()
      ..addAll(urls.map((url) {
        final existing = existingBySource[url];
        if (existing != null && existing.isNotEmpty) {
          return existing.removeAt(0);
        }
        return _EditableCollagePhoto(source: url);
      }));

    if (_activeEditorIndex != null &&
        _activeEditorIndex! >= _editablePhotos.length) {
      _activeEditorIndex = null;
    }
    return _editablePhotos;
  }

  List<CollagePhotoTransform> _currentPhotoTransforms() {
    return _editablePhotos
        .map((item) => item.transform)
        .toList(growable: false);
  }

  void _markCollagePreviewDirty() {
    _generatedCollageBytes = null;
    _hasFullQualityRender = false;
    _lastCompletedAutoGenerationFingerprint = null;
  }

  double _clampedEditorScale(double scale) => scale.clamp(1.0, 4.0).toDouble();

  Offset _clampedEditorOffset(Offset offset) {
    return Offset(
      offset.dx.clamp(-1.0, 1.0).toDouble(),
      offset.dy.clamp(-1.0, 1.0).toDouble(),
    );
  }

  void _selectEditablePhoto(int index) {
    if (index < 0 || index >= _editablePhotos.length) return;
    setState(() => _activeEditorIndex = index);
  }

  void _startFramePinch(int index, ScaleStartDetails details) {
    if (index < 0 || index >= _editablePhotos.length) return;
    final photo = _editablePhotos[index];
    _framePinchSession = _FramePinchSession(
      index: index,
      startOffset: photo.offset,
      startScale: photo.scale,
    );
    _selectEditablePhoto(index);
  }

  void _updateFramePinch(int index, ScaleUpdateDetails details) {
    final session = _framePinchSession;
    if (session == null ||
        session.index != index ||
        index >= _editablePhotos.length) {
      return;
    }
    final tileSize = _previewTileSize <= 0 ? 1.0 : _previewTileSize;
    setState(() {
      final photo = _editablePhotos[index];
      photo.scale = _clampedEditorScale(session.startScale * details.scale);
      final divisor = max(1.0, tileSize * 0.42 / photo.scale);
      photo.offset = _clampedEditorOffset(
        session.startOffset + details.focalPointDelta / divisor,
      );
      _markCollagePreviewDirty();
    });
    _scheduleAutoGenerate();
  }

  void _endFramePinch() {
    _framePinchSession = null;
  }

  void _resetEditablePhoto(int index) {
    if (index < 0 || index >= _editablePhotos.length) return;
    setState(() {
      final photo = _editablePhotos[index];
      photo.scale = 1;
      photo.offset = Offset.zero;
      _markCollagePreviewDirty();
    });
    _scheduleAutoGenerate(immediate: true);
  }

  void _setHoveredSwapTargetIndex(int? index) {
    if (_hoveredSwapTargetIndex == index) return;
    setState(() => _hoveredSwapTargetIndex = index);
  }

  void _swapEditablePhotos(int fromIndex, int toIndex) {
    if (fromIndex == toIndex ||
        fromIndex < 0 ||
        toIndex < 0 ||
        fromIndex >= _editablePhotos.length ||
        toIndex >= _editablePhotos.length) {
      return;
    }
    setState(() {
      final fromPhoto = _editablePhotos[fromIndex];
      _editablePhotos[fromIndex] = _editablePhotos[toIndex];
      _editablePhotos[toIndex] = fromPhoto;
      _activeEditorIndex = toIndex;
      _hoveredSwapTargetIndex = null;
      _markCollagePreviewDirty();
    });
    _scheduleAutoGenerate(immediate: true);
  }

  void _clearHoveredSwapTarget() {
    _setHoveredSwapTargetIndex(null);
  }

  CollageDecor _buildMemoryCollageDecor() {
    final items = _getFilteredMemoryItems();
    if (items.isEmpty) {
      return CollageDecor.memory(
        occasionLabel: 'Khoảnh khắc yêu thương',
        message: 'Những điều dịu dàng nhất luôn xứng đáng được lưu giữ.',
      );
    }

    final dates = items
        .map((item) => item['ts'] as int? ?? 0)
        .where((ts) => ts > 0)
        .map(DateTime.fromMillisecondsSinceEpoch)
        .toList()
      ..sort();

    if (dates.isEmpty) {
      return CollageDecor.memory(
        occasionLabel: _selectedMonth == 'all'
            ? 'Những ngày kỷ niệm'
            : 'Kỷ niệm ${_displayMonthLabel(_selectedMonth)}',
        message: 'Lời chúc nhỏ cho những khoảnh khắc đáng nhớ của hai bạn.',
      );
    }

    final distinctDays = dates
        .map((date) =>
            '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}')
        .toSet();

    if (distinctDays.length == 1) {
      final date = dates.first;
      return CollageDecor.memory(
        occasionLabel: 'Kỷ niệm ngày ${_formatDateLabel(date)}',
        message:
            'Chúc ngày kỷ niệm này luôn lấp lánh, ấm áp và đầy những cái nắm tay thật lâu.',
      );
    }

    if (_selectedMonth != 'all') {
      return CollageDecor.memory(
        occasionLabel: 'Kỷ niệm ${_displayMonthLabel(_selectedMonth)}',
        message:
            'Tháng yêu thương này lưu lại ${items.length} khoảnh khắc dịu dàng của hai bạn.',
      );
    }

    return CollageDecor.memory(
      occasionLabel: 'Những ngày mình thương nhau',
      message:
          'Mỗi khung hình là một lời chúc nhỏ để hành trình bên nhau luôn ngọt ngào và bền lâu.',
    );
  }

  String _defaultCollageTitle() {
    if (_isFromMemory) {
      return _selectedMonth == 'all'
          ? 'Kỷ niệm của chúng mình ❤️'
          : 'Kỷ niệm tháng ${_selectedMonth.split('-')[1]} ❤️';
    }
    return 'Khoảnh khắc đáng nhớ ❤️';
  }

  String _allMemoryPhotosLabel() =>
      'Tất cả ảnh kỷ niệm (${_memoryPhotos.length} ảnh)';

  String _monthMenuLabel(String key, int count) {
    final parts = key.split('-');
    if (parts.length != 2) {
      return '$key • $count ảnh';
    }
    return 'Tháng ${parts[1]}/${parts[0]} • $count ảnh';
  }

  _CollageAspectPreset get _activeAspectPreset {
    return _aspectPresets.firstWhere(
      (preset) => preset.id == _selectedAspectRatio,
      orElse: () => _aspectPresets[1],
    );
  }

  BorderRadius _paperRadius({bool flipped = false}) {
    return BorderRadius.only(
      topLeft: Radius.circular(flipped ? 20 : 24),
      topRight: Radius.circular(flipped ? 24 : 20),
      bottomLeft: Radius.circular(flipped ? 24 : 18),
      bottomRight: Radius.circular(flipped ? 18 : 26),
    );
  }

  List<BoxShadow> _paperShadow([Color color = _paperCocoa]) {
    return [
      BoxShadow(
        color: color.withValues(alpha: 0.08),
        blurRadius: 20,
        offset: const Offset(0, 10),
      ),
      BoxShadow(
        color: Colors.white.withValues(alpha: 0.55),
        blurRadius: 6,
        offset: const Offset(-2, -2),
      ),
    ];
  }

  BoxDecoration _paperPanelDecoration({
    Color color = _paperShell,
    Color borderColor = _paperLine,
    bool flipped = false,
  }) {
    return BoxDecoration(
      color: color,
      borderRadius: _paperRadius(flipped: flipped),
      border: Border.all(color: borderColor.withValues(alpha: 0.92), width: 1.2),
      boxShadow: _paperShadow(),
    );
  }

  TextStyle _editorialStyle({
    required double size,
    Color color = _paperInk,
    FontWeight fontWeight = FontWeight.w800,
    double? height,
    double? letterSpacing,
  }) {
    return GoogleFonts.playfairDisplay(
      fontSize: size,
      fontWeight: fontWeight,
      color: color,
      height: height,
      letterSpacing: letterSpacing,
    );
  }

  void _cacheDecodedImage(String key, ui.Image image) {
    final existing = _decodedImageCache[key];
    if (existing != null) {
      return;
    }

    _decodedImageCache[key] = image;
    if (_decodedImageCache.length <= 90) {
      return;
    }

    final oldestKey = _decodedImageCache.keys.first;
    final removed = _decodedImageCache.remove(oldestKey);
    if (removed == null || identical(removed, image)) {
      return;
    }
    try {
      removed.dispose();
    } catch (_) {}
  }

  CollageDecor _buildCollageDecor() {
    if (!_isFromMemory) {
      return CollageDecor.upload();
    }

    return _buildMemoryCollageDecor();
  }

  Future<void> _pickDevicePhotos() async {
    try {
      final picked = await AppLifecyclePresenceGuard.guard(
        () => ImagePickerRecoveryService.instance.pickMultiImage(
          picker: _picker,
          imageQuality: 80,
        ),
      );
      if (picked.isNotEmpty) {
        setState(() {
          _deviceFiles.addAll(picked);
          _markCollagePreviewDirty();
          if (_deviceFiles.length > 50) {
            _deviceFiles.removeRange(50, _deviceFiles.length);
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                  content: Text('Chỉ chọn tối đa 50 ảnh. Đã tự động cắt bớt.')),
            );
          }
        });
        _scheduleAutoGenerate();
      }
    } catch (e) {
      debugPrint('Error picking photos: $e');
    }
  }

  String _buildGenerationFingerprint(List<String> urls) {
    final normalizedStickers = _selectedStickers.toList()..sort();
    final transforms = _editablePhotos
        .map(
          (item) => [
            item.source,
            item.scale.toStringAsFixed(3),
            item.offset.dx.toStringAsFixed(3),
            item.offset.dy.toStringAsFixed(3),
          ].join('@'),
        )
        .join(';');
    return [
      _isFromMemory ? 'memory' : 'device',
      _selectedMonth,
      _selectedStyle,
      _selectedAspectRatio,
      _photoScale.toStringAsFixed(3),
      normalizedStickers.join(','),
      urls.length.toString(),
      Object.hashAll(urls).toString(),
      transforms,
    ].join('|');
  }

  int _nextCollageLayoutSeed() {
    final next = DateTime.now().microsecondsSinceEpoch & 0x7fffffff;
    return next == _collageLayoutSeed ? next + 1 : next;
  }

  void _scheduleAutoGenerate({bool immediate = false}) {
    _autoGenerateDebounceTimer?.cancel();
    final urls = _getFilteredUrls();
    if (urls.isEmpty) {
      _queuedAutoGenerationFingerprint = null;
      return;
    }

    _syncEditablePhotos(urls);
    final fingerprint = _buildGenerationFingerprint(urls);
    if (!_isGenerating &&
        fingerprint == _lastCompletedAutoGenerationFingerprint) {
      return;
    }

    _queuedAutoGenerationFingerprint = fingerprint;

    void trigger() {
      if (!mounted) return;
      if (_queuedAutoGenerationFingerprint != fingerprint) return;
      _generateCollage(
        triggeredAutomatically: true,
        expectedFingerprint: fingerprint,
        usePreviewQuality: true,
      );
    }

    if (immediate) {
      trigger();
    } else {
      _autoGenerateDebounceTimer =
          Timer(_autoGenerateDebounceDuration, trigger);
    }
  }

  String _decodedImageCacheKey(String sourceKey, int maxDimension) {
    return '$maxDimension::$sourceKey';
  }

  Future<ui.Image> _loadImage(
    dynamic source, {
    required int maxDimension,
  }) async {
    if (source is String && source.startsWith('http')) {
      final cacheKey = _decodedImageCacheKey(source, maxDimension);
      final cached = _decodedImageCache[cacheKey];
      if (cached != null) {
        return cached;
      }
      final image = await _loadCachedNetworkImage(
        source,
        maxDimension: maxDimension,
      );
      _cacheDecodedImage(cacheKey, image);
      return image;
    } else if (source is String) {
      final cacheKey = _decodedImageCacheKey(source, maxDimension);
      final cached = _decodedImageCache[cacheKey];
      if (cached != null) {
        return cached;
      }
      final bytes = await File(source).readAsBytes();
      final image = await _decodeImageBytes(
        bytes,
        maxDimension: maxDimension,
      );
      _cacheDecodedImage(cacheKey, image);
      return image;
    } else if (source is Uint8List) {
      return _decodeImageBytes(
        source,
        maxDimension: maxDimension,
      );
    } else {
      throw Exception('Unsupported image source');
    }
  }

  Future<ui.Image> _loadCachedNetworkImage(
    String url, {
    required int maxDimension,
  }) async {
    final provider = CachedNetworkImageProvider(
      url,
      maxWidth: maxDimension,
      maxHeight: maxDimension,
    );
    final stream = provider.resolve(const ImageConfiguration());
    final completer = Completer<ui.Image>();
    late ImageStreamListener listener;
    Timer? timeoutTimer;

    void cleanup() {
      timeoutTimer?.cancel();
      stream.removeListener(listener);
    }

    listener = ImageStreamListener(
      (imageInfo, _) {
        if (completer.isCompleted) return;
        cleanup();
        completer.complete(imageInfo.image);
      },
      onError: (error, stackTrace) {
        if (completer.isCompleted) return;
        cleanup();
        completer.completeError(error, stackTrace);
      },
    );

    timeoutTimer = Timer(const Duration(seconds: 18), () {
      if (completer.isCompleted) return;
      cleanup();
      completer.completeError(TimeoutException('Tải ảnh kỷ niệm quá lâu'));
    });

    stream.addListener(listener);
    return completer.future;
  }

  Future<ui.Image> _decodeImageBytes(
    Uint8List bytes, {
    required int maxDimension,
  }) async {
    final codec = await ui.instantiateImageCodec(
      bytes,
      targetWidth: maxDimension,
      targetHeight: maxDimension,
      allowUpscaling: false,
    );
    final frame = await codec.getNextFrame();
    return frame.image;
  }

  Future<List<ui.Image>> _loadImagesForCollage(
    List<String> urls,
    int requestId,
    int maxDimension,
  ) async {
    final images = <ui.Image>[];
    for (var index = 0; index < urls.length; index += _imageLoadBatchSize) {
      if (requestId != _generationTicket) {
        break;
      }
      final batch = urls.skip(index).take(_imageLoadBatchSize).toList();
      final loaded = await Future.wait(
        batch.map((url) async {
          try {
            if (requestId != _generationTicket) {
              return null;
            }
            return await _loadImage(
              url,
              maxDimension: maxDimension,
            );
          } catch (e) {
            debugPrint('Error loading image $url: $e');
            return null;
          }
        }),
      );
      images.addAll(loaded.whereType<ui.Image>());
      if (requestId != _generationTicket) {
        break;
      }
      await Future<void>.delayed(Duration.zero);
    }
    return images;
  }

  Future<void> _generateCollage({
    bool bypassDebounce = false,
    bool triggeredAutomatically = false,
    String? expectedFingerprint,
    bool usePreviewQuality = false,
    bool randomizeLayout = false,
  }) async {
    if (!bypassDebounce &&
        !triggeredAutomatically &&
        expectedFingerprint == null &&
        !usePreviewQuality) {
      _scheduleAutoGenerate();
      return;
    }

    final int requestId = ++_generationTicket;
    if (randomizeLayout) {
      _collageLayoutSeed = _nextCollageLayoutSeed();
    }
    final int layoutSeed = _collageLayoutSeed;
    _autoGenerateDebounceTimer?.cancel();
    var urls = _getFilteredUrls();
    final editablePhotos = _syncEditablePhotos(urls);
    urls = editablePhotos.map((item) => item.source).toList(growable: false);
    if (urls.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Không có ảnh nào để ghép.')),
      );
      return;
    }

    final fingerprint =
        expectedFingerprint ?? _buildGenerationFingerprint(urls);
    if (triggeredAutomatically &&
        !_isGenerating &&
        fingerprint == _lastCompletedAutoGenerationFingerprint) {
      return;
    }

    setState(() {
      _isGenerating = true;
    });

    try {
      // Limit to 50 photos randomly if too many from memory
      if (_isFromMemory && urls.length > 50) {
        urls = List<String>.from(urls)..shuffle(Random(layoutSeed ^ 0x19A7));
        urls = urls.take(50).toList();
      }

      final targetDecodeDimension = usePreviewQuality
          ? _collagePreviewDecodeMaxDimension
          : _collageDecodeMaxDimension;
      final uiImages = await _loadImagesForCollage(
        urls,
        requestId,
        targetDecodeDimension,
      );
      if (requestId != _generationTicket) {
        return;
      }
      if (uiImages.isEmpty) {
        throw Exception('Không tải được ảnh nào.');
      }

      final arrangedImages = uiImages;

      String title = _titleCtrl.text.trim();
      if (title.isEmpty) {
        title = _defaultCollageTitle();
      }

      final Uint8List? collageBytes = await CollageGenerator.generateCollage(
        arrangedImages,
        title,
        _selectedStyle,
        decor: _buildCollageDecor(),
        options: CollageRenderOptions(
          stickers: _selectedStickers.toList(),
          photoScale: _photoScale,
          outputAspectRatio: _activeAspectPreset.ratio,
          backgroundTheme: _selectedBackgroundTheme,
          layoutSeed: layoutSeed,
          renderQuality: usePreviewQuality
              ? CollageRenderQuality.preview
              : CollageRenderQuality.full,
          photoTransforms: editablePhotos
              .map((item) => item.transform)
              .toList(growable: false),
        ),
      );

      if (collageBytes != null && mounted && requestId == _generationTicket) {
        setState(() {
          _generatedCollageBytes = collageBytes;
          _hasFullQualityRender = !usePreviewQuality;
        });
        if (triggeredAutomatically) {
          _lastCompletedAutoGenerationFingerprint = fingerprint;
        }
      }
    } catch (e) {
      if (mounted && requestId == _generationTicket) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Lỗi: $e')),
        );
      }
    } finally {
      if (mounted && requestId == _generationTicket) {
        setState(() => _isGenerating = false);
      }
    }
  }

  Future<bool> _ensureFullQualityCollage() async {
    if (_generatedCollageBytes == null) {
      return false;
    }
    if (_hasFullQualityRender) {
      return true;
    }

    await _generateCollage(
      bypassDebounce: true,
      usePreviewQuality: false,
    );
    return _generatedCollageBytes != null && _hasFullQualityRender;
  }

  Future<void> _saveImage() async {
    if (_generatedCollageBytes == null) return;
    final canProceed = await CollageLimitService().checkLimitAndAskAd(context);
    if (!mounted || !canProceed) return;
    final hasFullQuality = await _ensureFullQualityCollage();
    if (!mounted || !hasFullQuality || _generatedCollageBytes == null) return;
    try {
      final String name =
          'soullocket_collage_${DateTime.now().millisecondsSinceEpoch}';
      final result = await VisionGallerySaver.saveImage(
        _generatedCollageBytes!,
        quality: 100,
        name: name,
        androidRelativePath: 'Pictures/SoulLocket/Collage',
      );

      final isSuccess = result['isSuccess'] == true ||
          (result['filePath']?.toString().isNotEmpty ?? false);

      if (mounted) {
        if (isSuccess) {
          await CollageLimitService().consumeLimit();
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
                content: Text('Đã lưu ảnh thành công vào thiết bị 💖')),
          );
        } else {
          final message = result['errorMessage']?.toString();
          throw Exception(
              message?.isNotEmpty == true ? message : 'Lỗi khi lưu ảnh');
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Lỗi: $e')),
        );
      }
    }
  }

  Future<void> _shareImage() async {
    if (_generatedCollageBytes == null) return;
    final canProceed = await CollageLimitService().checkLimitAndAskAd(context);
    if (!mounted || !canProceed) return;
    final hasFullQuality = await _ensureFullQualityCollage();
    if (!mounted || !hasFullQuality || _generatedCollageBytes == null) return;
    try {
      final dir = await getTemporaryDirectory();
      final path =
          '${dir.path}/collage_${DateTime.now().millisecondsSinceEpoch}.png';
      final file = File(path);
      await file.writeAsBytes(_generatedCollageBytes!);

      await Share.shareXFiles(
        [XFile(path)],
        text: 'Kỷ niệm của chúng mình 💖',
      );
      await CollageLimitService().consumeLimit();
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Lỗi khi chia sẻ: $e')),
        );
      }
    }
  }

  Future<void> _showGeneratedCollagePreview() async {
    final bytes = _generatedCollageBytes;
    if (bytes == null) return;
    await _showZoomPreview(
      child: Image.memory(
        bytes,
        fit: BoxFit.contain,
        filterQuality: FilterQuality.high,
      ),
      title: 'Xem ảnh ghép',
      fullScreen: true,
    );
  }

  Future<void> _showSourcePhotoPreview(String url) async {
    await _showZoomPreview(
      child: url.startsWith('http')
          ? CachedNetworkImage(
              memCacheWidth: 1440,
              imageUrl: url,
              fit: BoxFit.contain,
              filterQuality: FilterQuality.high,
              placeholder: (context, url) =>
                  const Center(child: CircularProgressIndicator()),
              errorWidget: (context, url, error) => const Icon(
                Icons.broken_image,
                color: Colors.white,
                size: 48,
              ),
            )
          : Image.file(
              File(url),
              fit: BoxFit.contain,
              filterQuality: FilterQuality.high,
            ),
      title: 'Xem ảnh',
    );
  }

  Future<void> _showZoomPreview({
    required Widget child,
    required String title,
    bool fullScreen = false,
  }) async {
    await showDialog<void>(
      context: context,
      builder: (context) {
        final size = MediaQuery.sizeOf(context);
        final topPadding = MediaQuery.paddingOf(context).top;
        final previewContent = Stack(
          children: [
            Positioned.fill(
              child: InteractiveViewer(
                minScale: 0.8,
                maxScale: 5,
                child: Center(child: child),
              ),
            ),
            Positioned(
              left: 14,
              right: 64,
              top: fullScreen ? topPadding + 12 : 12,
              child: Text(
                '$title • kéo 2 ngón để phóng to',
                maxLines: 1,
                overflow: TextOverflow.ellipsis,
                style: SLTheme.quicksand(
                  color: Colors.white.withValues(alpha: 0.82),
                  fontWeight: FontWeight.w800,
                ),
              ),
            ),
            Positioned(
              top: fullScreen ? topPadding + 8 : 8,
              right: 8,
              child: IconButton.filled(
                onPressed: () => Navigator.pop(context),
                style: IconButton.styleFrom(
                  backgroundColor: Colors.white.withValues(alpha: 0.14),
                  foregroundColor: Colors.white,
                ),
                icon: const Icon(Icons.close),
              ),
            ),
          ],
        );

        if (fullScreen) {
          return Material(
            color: const Color(0xFF0F172A),
            child: SizedBox(
              width: size.width,
              height: size.height,
              child: previewContent,
            ),
          );
        }

        return Dialog(
          backgroundColor: Colors.transparent,
          insetPadding: const EdgeInsets.all(12),
          child: Container(
            width: size.width,
            height: size.height * 0.86,
            decoration: BoxDecoration(
              color: const Color(0xFF0F172A),
              borderRadius: BorderRadius.circular(24),
            ),
            clipBehavior: Clip.hardEdge,
            child: previewContent,
          ),
        );
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.sizeOf(context).width;
    final isPhoneWidth = screenWidth < 430;
    final horizontalPadding = screenWidth < 360
        ? 14.0
        : screenWidth < 430
            ? 16.0
            : 24.0;

    return Scaffold(
      backgroundColor: _paperCream,
      appBar: AppBar(
        backgroundColor: _paperCream.withValues(alpha: 0.90),
        elevation: 0,
        surfaceTintColor: Colors.transparent,
        leadingWidth: 72,
        leading: Padding(
          padding: const EdgeInsets.only(left: 16, top: 6, bottom: 6),
          child: IconButton(
            style: IconButton.styleFrom(
              backgroundColor: _paperShell,
              foregroundColor: _paperInk,
              shape: RoundedRectangleBorder(borderRadius: _paperRadius()),
            ),
            icon: const Icon(Icons.arrow_back_ios_new),
            onPressed: () => Navigator.pop(context),
          ),
        ),
        title: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Transform.rotate(
              angle: -0.04,
              child: _IntroChip(
                label: 'Postcard Studio',
                fixedHeight: isPhoneWidth ? 30 : 32,
              ),
            ),
            const SizedBox(height: 4),
            Text(
              'Memory Collage',
              style: _editorialStyle(
                size: isPhoneWidth ? 21 : 23,
                color: _paperInk,
                fontWeight: FontWeight.w800,
              ),
            ),
          ],
        ),
        centerTitle: true,
      ),
      body: Stack(
        children: [
          Positioned.fill(
            child: IgnorePointer(
              child: CustomPaint(painter: _MemoryMascotBackgroundPainter()),
            ),
          ),
          SingleChildScrollView(
            padding: EdgeInsets.fromLTRB(
              horizontalPadding,
              24,
              horizontalPadding,
              max(40, MediaQuery.paddingOf(context).bottom + 32),
            ),
            child: LayoutBuilder(
              builder: (context, constraints) {
                final safeContentWidth = max(0.0, constraints.maxWidth);
                final contentWidth = isPhoneWidth
                    ? max(0.0, safeContentWidth - 6.0)
                    : min(680.0, safeContentWidth);
                return Align(
                  alignment: Alignment.topCenter,
                  child: SizedBox(
                    width: contentWidth,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.center,
                      children: [
                        _buildIntroCard(),
                        SLSpacing.h24,

                        // Tabs
                        _buildSourceModeTabs(compact: isPhoneWidth),
                        SLSpacing.h24,

                        if (_isFromMemory) ...[
                          Text(
                            'Chọn mốc thời gian:',
                            style: SLTheme.quicksand(
                                fontWeight: FontWeight.w700,
                                color: _paperInk,
                                fontSize: 15),
                          ),
                          SLSpacing.h8,
                          LayoutBuilder(
                            builder: (context, dropdownConstraints) {
                              final dropdownFontSize =
                                  dropdownConstraints.maxWidth < 340
                                      ? 13.6
                                      : 15.0;
                              final monthLabels = <String>[
                                _allMemoryPhotosLabel(),
                                ..._availableMonths.map((m) {
                                  final parts = m.split('-');
                                  final count = _memoryPhotos.where((item) {
                                    final ts = item['ts'] as int? ?? 0;
                                    if (ts == 0) return false;
                                    final d =
                                        DateTime.fromMillisecondsSinceEpoch(
                                      ts,
                                    );
                                    return d.year == int.parse(parts[0]) &&
                                        d.month == int.parse(parts[1]);
                                  }).length;
                                  return _monthMenuLabel(m, count);
                                }),
                              ];

                              Text buildDropdownLabel(String label) {
                                return Text(
                                  label,
                                  maxLines: 1,
                                  overflow: TextOverflow.ellipsis,
                                  softWrap: false,
                                  style: SLTheme.quicksand(
                                    fontSize: dropdownFontSize,
                                    fontWeight: FontWeight.w700,
                                    color: _paperInk,
                                  ),
                                );
                              }

                              return Container(
                                constraints:
                                    const BoxConstraints(minHeight: 56),
                                padding: const EdgeInsets.symmetric(
                                    horizontal: 14, vertical: 6),
                                decoration: _paperPanelDecoration(
                                  color: const Color(0xFFFFF8F2),
                                  borderColor: const Color(0xFFDCC9B8),
                                  flipped: true,
                                ),
                                child: DropdownButtonHideUnderline(
                                  child: DropdownButton<String>(
                                    isExpanded: true,
                                    isDense: true,
                                    menuMaxHeight: 360,
                                    value: _selectedMonth,
                                    selectedItemBuilder: (_) => monthLabels
                                        .map(
                                          (label) => Align(
                                            alignment: Alignment.centerLeft,
                                            child: buildDropdownLabel(label),
                                          ),
                                        )
                                        .toList(growable: false),
                                    items: [
                                      DropdownMenuItem(
                                        value: 'all',
                                        child: buildDropdownLabel(
                                          _allMemoryPhotosLabel(),
                                        ),
                                      ),
                                      ..._availableMonths.map((m) {
                                        final parts = m.split('-');
                                        final count =
                                            _memoryPhotos.where((item) {
                                          final ts = item['ts'] as int? ?? 0;
                                          if (ts == 0) return false;
                                          final d = DateTime
                                              .fromMillisecondsSinceEpoch(ts);
                                          return d.year ==
                                                  int.parse(parts[0]) &&
                                              d.month == int.parse(parts[1]);
                                        }).length;
                                        return DropdownMenuItem(
                                          value: m,
                                          child: buildDropdownLabel(
                                            _monthMenuLabel(m, count),
                                          ),
                                        );
                                      }),
                                    ],
                                    onChanged: (val) {
                                      if (val != null) {
                                        setState(() {
                                          _selectedMonth = val;
                                          _generatedCollageBytes = null;
                                          _hasFullQualityRender = false;
                                        });
                                        _scheduleAutoGenerate();
                                      }
                                    },
                                  ),
                                ),
                              );
                            },
                          ),
                          SLSpacing.h8,
                          Text(
                            'Khung tự thêm lời chúc; ảnh kỷ niệm đã tải sẽ được cache theo URL để lần tạo sau đỡ tốn mạng.',
                            style: SLTheme.quicksand(
                              fontSize: 12.5,
                              fontWeight: FontWeight.w600,
                              color: _paperRoseDeep,
                              height: 1.35,
                            ),
                          ),
                        ] else ...[
                          Text(
                            'Chọn bộ ảnh riêng:',
                            style: SLTheme.quicksand(
                                fontWeight: FontWeight.w700,
                                color: _paperInk,
                                fontSize: 15),
                          ),
                          SLSpacing.h8,
                          GestureDetector(
                            behavior: HitTestBehavior.opaque,
                            onTap: _pickDevicePhotos,
                            child: Container(
                              height: 100,
                              decoration: _paperPanelDecoration(
                                color: const Color(0xFFFFF7EE),
                                borderColor: const Color(0xFFD8C7B7),
                              ),
                              alignment: Alignment.center,
                              child: Column(
                                mainAxisAlignment: MainAxisAlignment.center,
                                children: [
                                  const Icon(Icons.cloud_upload,
                                      color: _paperRoseDeep, size: 32),
                                  SLSpacing.h8,
                                  Text('Chạm để chọn ảnh yêu thích',
                                      style: SLTheme.quicksand(
                                          fontSize: 14,
                                          fontWeight: FontWeight.bold,
                                          color: _paperMuted)),
                                ],
                              ),
                            ),
                          ),
                          SLSpacing.h8,
                          Text(
                            'Bộ ảnh tự chọn vẫn có khung hoạt hình, nền pastel và tiêu đề nổi bật.',
                            style: SLTheme.quicksand(
                              fontSize: 12.5,
                              fontWeight: FontWeight.w600,
                              color: _paperMuted,
                              height: 1.35,
                            ),
                          ),
                        ],

                        SLSpacing.h24,
                        _buildSelectedImagesPreview(),

                        SLSpacing.h24,
                        Text(
                          'Chọn kiểu khung:',
                          style: SLTheme.quicksand(
                              fontWeight: FontWeight.w700,
                              color: _paperInk,
                              fontSize: 15),
                        ),
                        SLSpacing.h8,
                        SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: Row(
                            children: [
                              _buildStyleOption(
                                  'grid', Icons.grid_on, 'Lưới sạch'),
                              SLSpacing.w12,
                              _buildStyleOption(
                                  'masonry', Icons.view_quilt, 'So le'),
                              SLSpacing.w12,
                              _buildStyleOption('polaroid', Icons.photo_library,
                                  'Album giấy'),
                              SLSpacing.w12,
                              _buildStyleOption('scatter',
                                  Icons.auto_awesome_mosaic, 'Tự do'),
                              SLSpacing.w12,
                              _buildStyleOption(
                                  'heart', Icons.favorite, 'Trái tim'),
                              SLSpacing.w12,
                              _buildStyleOption(
                                  'story', Icons.view_agenda, 'Dọc nổi bật'),
                              SLSpacing.w12,
                              _buildStyleOption(
                                  'poster', Icons.wallpaper, 'Ngang tạp chí'),
                            ],
                          ),
                        ),

                        SLSpacing.h24,
                        _buildBackgroundThemePicker(),

                        SLSpacing.h24,
                        _buildAspectRatioSelector(),

                        SLSpacing.h24,
                        _buildStickerPicker(),

                        SLSpacing.h24,
                        _buildPhotoSizeControl(),

                        SLSpacing.h24,
                        Text(
                          'Tiêu đề (tuỳ chọn):',
                          style: SLTheme.quicksand(
                              fontWeight: FontWeight.w700,
                              color: _paperInk,
                              fontSize: 15),
                        ),
                        SLSpacing.h8,
                        TextField(
                          controller: _titleCtrl,
                          decoration: InputDecoration(
                            hintText: 'VD: Những ngày thật đẹp ❤️',
                            hintStyle: SLTheme.quicksand(
                                color: Colors.grey[400], fontSize: 15),
                            contentPadding: const EdgeInsets.symmetric(
                                horizontal: 16, vertical: 14),
                            border: OutlineInputBorder(
                              borderRadius: _paperRadius(),
                              borderSide: const BorderSide(color: _paperLine),
                            ),
                            enabledBorder: OutlineInputBorder(
                              borderRadius: _paperRadius(),
                              borderSide: const BorderSide(color: _paperLine),
                            ),
                            focusedBorder: OutlineInputBorder(
                              borderRadius: _paperRadius(),
                              borderSide:
                                  const BorderSide(color: _paperRoseDeep),
                            ),
                            filled: true,
                            fillColor: const Color(0xFFFFF8F2),
                          ),
                        ),
                        SLSpacing.h8,
                        Text(
                          'Tiêu đề trong ảnh sẽ nằm trên dải "KHOẢNH KHẮC ĐẶC BIỆT" để nhìn vào là thấy đây là dấu mốc đáng nhớ.',
                          style: SLTheme.quicksand(
                            fontSize: 12.5,
                            fontWeight: FontWeight.w600,
                            color: _paperCocoa,
                            height: 1.35,
                          ),
                        ),
                        SLSpacing.gapH(32),

                        if (_generatedCollageBytes != null) ...[
                          Container(
                            padding: const EdgeInsets.fromLTRB(14, 14, 14, 16),
                            decoration: _paperPanelDecoration(
                              color: const Color(0xFFFFF8F2),
                              borderColor: const Color(0xFFDCC9B8),
                              flipped: true,
                            ),
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  'Bản xem trước collage',
                                  style: _editorialStyle(
                                    size: 18,
                                    color: _paperInk,
                                    fontWeight: FontWeight.w800,
                                  ),
                                ),
                                SLSpacing.h8,
                                Text(
                                  'Nhấn vào ảnh để xem lớn hơn trước khi lưu hoặc chia sẻ.',
                                  style: SLTheme.quicksand(
                                    fontSize: 12.5,
                                    fontWeight: FontWeight.w700,
                                    color: _paperMuted,
                                    height: 1.4,
                                  ),
                                ),
                                SLSpacing.h12,
                                RepaintBoundary(
                                  child: GestureDetector(
                                    onTap: _showGeneratedCollagePreview,
                                    child: Container(
                                      decoration: BoxDecoration(
                                        color: const Color(0xFFF7EBDD),
                                        borderRadius: _paperRadius(),
                                        border: Border.all(color: _paperLine),
                                        boxShadow: [
                                          BoxShadow(
                                            color:
                                                _paperCocoa.withValues(alpha: 0.10),
                                            blurRadius: 22,
                                            offset: const Offset(0, 12),
                                          )
                                        ],
                                      ),
                                      clipBehavior: Clip.hardEdge,
                                      child: Stack(
                                        alignment: Alignment.bottomCenter,
                                        children: [
                                          ConstrainedBox(
                                            constraints: const BoxConstraints(
                                              minHeight: 240,
                                              maxHeight: 620,
                                            ),
                                            child: Image.memory(
                                              _generatedCollageBytes!,
                                              width: double.infinity,
                                              fit: BoxFit.contain,
                                              alignment: Alignment.topCenter,
                                              filterQuality: FilterQuality.high,
                                            ),
                                          ),
                                          Positioned(
                                            left: 12,
                                            right: 12,
                                            bottom: 12,
                                            child: Container(
                                              padding:
                                                  const EdgeInsets.symmetric(
                                                      horizontal: 12,
                                                      vertical: 8),
                                              decoration: BoxDecoration(
                                                color: _paperCocoa
                                                    .withValues(alpha: 0.78),
                                                borderRadius:
                                                    _paperRadius(flipped: true),
                                              ),
                                              child: Row(
                                                mainAxisSize: MainAxisSize.min,
                                                mainAxisAlignment:
                                                    MainAxisAlignment.center,
                                                children: [
                                                  const Icon(Icons.zoom_in,
                                                      color: Colors.white,
                                                      size: 18),
                                                  SLSpacing.w8,
                                                  Text(
                                                    'Ấn để xem phóng to',
                                                    style: SLTheme.quicksand(
                                                      color: Colors.white,
                                                      fontWeight:
                                                          FontWeight.w800,
                                                      fontSize: 12.5,
                                                    ),
                                                  ),
                                                ],
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                          SLSpacing.h24,
                          Row(
                            children: [
                              Expanded(
                                child: ElevatedButton.icon(
                                  onPressed: _isGenerating
                                      ? null
                                      : () => _generateCollage(
                                            bypassDebounce: true,
                                            usePreviewQuality: false,
                                            randomizeLayout: true,
                                          ),
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: const Color(0xFFEDE2D6),
                                    foregroundColor: _paperInk,
                                    padding: const EdgeInsets.symmetric(
                                        vertical: 16),
                                    shape: RoundedRectangleBorder(
                                        borderRadius:
                                            _paperRadius(flipped: true)),
                                    elevation: 0,
                                  ),
                                  icon: _isGenerating
                                      ? const SizedBox(
                                          width: 20,
                                          height: 20,
                                          child: CircularProgressIndicator(
                                              strokeWidth: 2))
                                      : const Icon(Icons.refresh),
                                  label: Text(
                                    'Tạo lại',
                                    style: SLTheme.quicksand(
                                        fontWeight: FontWeight.w800,
                                        fontSize: 16),
                                  ),
                                ),
                              ),
                            ],
                          ),
                          SLSpacing.h16,
                          Row(
                            children: [
                              Expanded(
                                child: ElevatedButton.icon(
                                  onPressed: _saveImage,
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: _paperRoseDeep,
                                    foregroundColor: Colors.white,
                                    padding: const EdgeInsets.symmetric(
                                        vertical: 16),
                                    shape: RoundedRectangleBorder(
                                        borderRadius: _paperRadius()),
                                    elevation: 0,
                                  ),
                                  icon: const Icon(Icons.save_alt),
                                  label: Text(
                                    'Lưu ảnh',
                                    style: SLTheme.quicksand(
                                        fontWeight: FontWeight.w800,
                                        fontSize: 16),
                                  ),
                                ),
                              ),
                              SLSpacing.w16,
                              Expanded(
                                child: ElevatedButton.icon(
                                  onPressed: _shareImage,
                                  style: ElevatedButton.styleFrom(
                                    backgroundColor: _paperMistDeep,
                                    foregroundColor: Colors.white,
                                    padding: const EdgeInsets.symmetric(
                                        vertical: 16),
                                    shape: RoundedRectangleBorder(
                                        borderRadius:
                                            _paperRadius(flipped: true)),
                                    elevation: 0,
                                  ),
                                  icon: const Icon(Icons.share),
                                  label: Text(
                                    'Chia sẻ',
                                    style: SLTheme.quicksand(
                                        fontWeight: FontWeight.w800,
                                        fontSize: 16),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ] else ...[
                          ElevatedButton.icon(
                            onPressed: _isGenerating
                                ? null
                                : () => _generateCollage(
                                      bypassDebounce: true,
                                      usePreviewQuality: false,
                                      randomizeLayout: true,
                                    ),
                            style: ElevatedButton.styleFrom(
                              backgroundColor: _paperRoseDeep,
                              foregroundColor: Colors.white,
                              padding: const EdgeInsets.symmetric(vertical: 16),
                              shape: RoundedRectangleBorder(
                                  borderRadius: _paperRadius()),
                              elevation: 0,
                            ),
                            icon: _isGenerating
                                ? const SizedBox(
                                    width: 20,
                                    height: 20,
                                    child: CircularProgressIndicator(
                                        strokeWidth: 2, color: Colors.white))
                                : const Icon(Icons.auto_awesome),
                            label: Text(
                              _isGenerating
                                  ? 'Đang tạo Collage...'
                                  : 'Tạo Collage',
                              style: SLTheme.quicksand(
                                  fontWeight: FontWeight.w800, fontSize: 16),
                            ),
                          ),
                        ],
                        SLSpacing.gapH(40),
                      ],
                    ),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
