part of '../community_tab.dart';

const int _communityPostMaxLength = 300;
const int _communityCommentMaxLength = 180;
const int _communitySearchHistoryLimit = 10;
const String _communitySearchHistoryPrefsKey = 'community_search_history_v1';
const String _communityHiddenPostsPrefsKey = 'community_hidden_posts_v1';
const String _communityAnniversaryMemoryShownPrefsKey =
    'community_anniversary_memory_shown_v1';
const String _communityMessengerButtonOffsetXPrefsKey =
    'community_messenger_button_offset_x_v1';
const String _communityMessengerButtonOffsetYPrefsKey =
    'community_messenger_button_offset_y_v1';
const bool _communityClosedUntilNextVersion = false;
// Toggle this flag when you want to quickly hide/show the community feed modules.
const bool _communityPreviewModeEnabled = false;
const Set<String> _communityPreviewFeedTypes = <String>{
  'foryou',
  'locket',
  'global',
  'friends',
  'hot',
};
bool _isCommunityPreviewFeed(String value) =>
    _communityPreviewModeEnabled && _communityPreviewFeedTypes.contains(value);
final DateFormat _kCommunityPostDateFormat = DateFormat('dd/MM/yyyy HH:mm');
final List<String> _communityGuidelinesVi = <String>[
  L10nService().translate('home_gililvnmin_c86035'),
  L10nService().translate('home_khngngnidu_c77b90'),
  L10nService().translate('home_khngcngkha_9e3928'),
];
const List<String> _communityGuidelinesEn = <String>[
  'Keep the tone respectful. No harassment or personal attacks.',
  'Do not post 18+, scam, spam, or harmful content.',
  'Do not expose anyone else\'s private information.',
];

bool _communityIsEnglish() => L10nService().locale.languageCode == 'en';

String _ct(String vi, String en) => _communityIsEnglish() ? en : vi;

String _ctf(
  String vi,
  String en, [
  Map<String, Object?> params = const {},
]) {
  var value = _ct(vi, en);
  params.forEach((name, replacement) {
    value = value.replaceAll('{$name}', '${replacement ?? ''}');
  });
  return value;
}

String _communityActionErrorMessage(
  dynamic error, {
  required String viFallback,
  required String enFallback,
}) {
  final info = AppErrorMapper.resolve(
    error,
    fallbackMessage: _ct(viFallback, enFallback),
  );
  final message = info.message.trim();
  final normalized = message.toLowerCase();

  if (normalized.contains('permission-denied') ||
      normalized.contains(L10nService().translate('home_khngcquyn_1955eb')) ||
      normalized.contains('khong co quyen') ||
      normalized.contains('permission')) {
    return _ct(
      L10nService().translate('home_mychangchn_92c1c8'),
      'The server is blocking this action. This is usually caused by an invalid active house, a community block on the account, or community restrictions on the server.',
    );
  }

  return message.isEmpty ? _ct(viFallback, enFallback) : message;
}

List<String> _communityGuidelines() =>
    _communityIsEnglish() ? _communityGuidelinesEn : _communityGuidelinesVi;
List<String> _blockedCommunityTerms = <String>[
  '18+',
  'khieu dam',
  'sex',
  'clip nong',
  'nude',
  'au dam',
  'child porn',
  'csam',
  'hiep dam',
  'rape',
  'dit',
  L10nService().translate('home_t_3171fd'),
  'lon',
  L10nService().translate('home_ln_c66fa6'),
  'cac',
  L10nService().translate('home_cc_0b235c'),
  'buoi',
  L10nService().translate('home_bui_232277'),
  'cc',
  'cl',
  'vcl',
  'dcm',
  L10nService().translate('home_cm_8d28f4'),
  'vkl',
  'vl',
  'loz',
  L10nService().translate('home_m_cf1d87'),
  'dm',
  L10nService().translate('home_txt_da27bc'),
  'di',
  'cave',
  L10nService().translate('home_ph_5bea54'),
  'pho',
  L10nService().translate('home_chch_9d9106'),
  'chich',
  L10nService().translate('home_nng_0dc53f'),
  'nung',
  L10nService().translate('home_dm_4f8dd4'),
  'dam',
  'thu dam',
  L10nService().translate('home_thdm_92b0ca'),
  'quay tay',
  'mbbg',
  'sgbb',
  'sgdd',
  L10nService().translate('home_chi_1d8a79'),
  L10nService().translate('home_chuith_e23740'),
  L10nService().translate('home_chith_f215b4'),
  L10nService().translate('home_tm_3c034b'),
  'dit me',
  L10nService().translate('home_con_655ea0'),
  'con di',
  L10nService().translate('home_thngch_c392ee'),
  'thang cho',
  L10nService().translate('home_cc_d9cdc2'),
  L10nService().translate('home_ct_7733ff'),
  L10nService().translate('home_txt_70b3fa'),
  L10nService().translate('home_m_9ec17b'),
  L10nService().translate('home_m_2e7399'),
  'du ma',
  'du me',
  L10nService().translate('home_cln_ee86fa'),
  'cu lon',
  L10nService().translate('home_mtln_2523d0'),
  'mat lon',
  L10nService().translate('home_hmln_117a8b'),
  'ham lon',
  L10nService().translate('home_viln_c54db8'),
  'vai lon',
  L10nService().translate('home_ciln_9a7be8'),
  'cai lon',
  L10nService().translate('home_ccch_4345ed'),
  'cac cho',
  L10nService().translate('home_ngunhch_8b6470'),
  'ngu nhu cho',
  L10nService().translate('home_cch_8a2417'),
  'oc cho',
  L10nService().translate('home_ub_5bc9fb'),
  'dau bo',
  L10nService().translate('home_bcu_2063bc'),
  'bu cu',
  L10nService().translate('home_sccc_25571b'),
  'suc cac',
  L10nService().translate('home_thmdu_da530c'),
  'tham du',
  L10nService().translate('home_nngln_78d8fc'),
  'nung lon',
  L10nService().translate('home_nngcc_321db9'),
  'nung cac',
  L10nService().translate('home_dmng_0c9251'),
  'dam dang',
  L10nService().translate('home_im_0d97ff'),
  'di diem',
  L10nService().translate('home_imthi_5ca365'),
  'diem thui',
  L10nService().translate('home_ch_caf035'),
  'cho de',
  L10nService().translate('home_chttit_58aefa'),
  'chet tiet',
  L10nService().translate('home_khnnn_37adcd'),
  'khon nan',
  L10nService().translate('home_mtdy_a6e71a'),
  'mat day',
  L10nService().translate('home_vgiodc_187cf1'),
  'vo giao duc',
  L10nService().translate('home_ch_f0b8a7'),
  'di cho',
  L10nService().translate('home_phphch_53b514'),
  'pho phach',
  L10nService().translate('home_lnmmy_f8c7cb'),
  'lon me may',
  L10nService().translate('home_cctao_3cac54'),
  'cac tao',
  L10nService().translate('home_tc_4ec555'),
  'dit cu',
  L10nService().translate('home_tb_70d7ff'),
  'dit ba',
  L10nService().translate('home_tcha_cb9ecc'),
  'dit cha',
  L10nService().translate('home_tconm_c0b0b2'),
  'dit con me',
  L10nService().translate('home_mm_446151'),
  'dmm',
  L10nService().translate('home_km_2247d5'),
  'dkm',
  'vcc',
  L10nService().translate('home_viccc_c26458'),
  'vai ca cac',
  L10nService().translate('home_o_19f964'),
  'deo',
  'bitch',
  'fuck',
  'shit',
  'asshole',
  'cunt',
  'dick',
  'pussy',
  'whore',
  'slut',
  'motherfucker',
  'bastard',
  'suck',
  'blowjob',
  'handjob',
  'tits',
  'boobs',
  'vagina',
  'penis',
  L10nService().translate('home_chchxgiao_a08c2d'),
  'chich xa giao',
  'some',
  'swing',
  'ons',
  'fnb',
  'fwb',
  '4`',
  L10nService().translate('home_txt_d2765f'),
  'd!',
  'l*n',
  'c*c',
  'b**i',
  L10nService().translate('home_t_907603'),
  'vkl',
  'vl',
  'v l',
  'v c l',
  'd c m',
  'd k m',
  'ml',
  L10nService().translate('home_mtl_d18c93'),
  'mat lo',
  L10nService().translate('home_hmti_267674'),
  'ham tai',
  L10nService().translate('home_nguhc_7a56fc'),
  'ngu hoc',
  L10nService().translate('home_nn_5e8f33'),
  'dan don',
  L10nService().translate('home_thiunng_9af63e'),
  'thieu nang',
  L10nService().translate('home_bnhhon_dee226'),
  'benh hoan',
  L10nService().translate('home_binthi_84c248'),
  'bien thai',
  L10nService().translate('home_udm_9784bc'),
  'au dam',
  L10nService().translate('home_hipdm_358249'),
  'hiep dam',
  L10nService().translate('home_thngt_37c343'),
  'thong dit',
  L10nService().translate('home_chilnh_e540c6'),
  'choi lo nhi',
  L10nService().translate('home_bodm_24c4be'),
  'bao dam',
  L10nService().translate('home_bohnh_c913da'),
  'bao hanh',
  L10nService().translate('home_nhln_7bff97'),
  'danh lon',
  L10nService().translate('home_chmnhau_99bb7c'),
  'chem nhau',
  L10nService().translate('home_gitngi_9155b7'),
  'giet nguoi',
  L10nService().translate('home_tt_c78ec0'),
  'tu tu',
  L10nService().translate('home_tst_2f688d'),
  'tu sat',
  L10nService().translate('home_maty_62361e'),
  'ma tuy',
  L10nService().translate('home_p_1489d2'),
  'dap da',
  L10nService().translate('home_htcn_2846fe'),
  'hut can',
  L10nService().translate('home_chi_e920e0'),
  'choi do',
  L10nService().translate('home_phcn_4408d0'),
  'phe can',
  L10nService().translate('home_koke_a66603'),
  'keo ke',
  L10nService().translate('home_htke_55eb2b'),
  'hit ke',
  L10nService().translate('home_baylc_0d4b81'),
  'bay lac',
  L10nService().translate('home_midm_0f44d0'),
  'mai dam',
  L10nService().translate('home_gigi_94fad5'),
  'gai goi',
  'trai bao',
  'trai bao',
  L10nService().translate('home_bndm_e1e2bf'),
  'ban dam',
  L10nService().translate('home_muadm_0aeb99'),
  'mua dam',
  L10nService().translate('home_migii_7176d5'),
  'moi gioi',
  L10nService().translate('home_tb_1bf90b'),
  'tu ba',
  L10nService().translate('home_tng_9765d9'),
  'tu ong',
  L10nService().translate('home_nhbc_632671'),
  'danh bac',
  L10nService().translate('home_cbc_62644e'),
  'co bac',
  L10nService().translate('home_c_323730'),
  'ca do',
  L10nService().translate('home_tixu_9c73c3'),
  'tai xiu',
  L10nService().translate('home_l_b578b0'),
  'lo de',
  L10nService().translate('home_xs_da3ea8'),
  'xo so',
  L10nService().translate('home_g_f4ce5f'),
  'da ga',
  L10nService().translate('home_phnng_821568'),
  'phan dong',
  L10nService().translate('home_chngph_3bba31'),
  'chong pha',
  L10nService().translate('home_khngb_622245'),
  'khung bo',
  L10nService().translate('home_bommn_b17893'),
  'bom min',
  L10nService().translate('home_vkh_344c7b'),
  'vu khi',
  L10nService().translate('home_sngn_ad5654'),
  'sung dan',
  L10nService().translate('home_daokim_50a2f0'),
  'dao kiem',
  L10nService().translate('home_bunlu_caafcb'),
  'buon lau',
  L10nService().translate('home_lao_415dda'),
  'lua dao',
  L10nService().translate('home_chimot_2bfcd1'),
  'chiem doat',
  L10nService().translate('home_tngtin_772b43'),
  'tong tien',
  L10nService().translate('home_btcc_fa4faa'),
  'bat coc',
  L10nService().translate('home_mcti_fe4a03'),
  'moc tui',
  L10nService().translate('home_trmcp_028124'),
  'trom cap',
  L10nService().translate('home_cpgit_460406'),
  'cuop giat',
  L10nService().translate('home_hipgit_cbb31f'),
  'hiep giet',
  L10nService().translate('home_phnxc_11d875'),
  'phan xac',
  L10nService().translate('home_mume_c88709'),
  'mau me',
  L10nService().translate('home_kinhd_0761cc'),
  'kinh di',
  L10nService().translate('home_tmlm_e33204'),
  'tom lom',
  L10nService().translate('home_gmghic_d475aa'),
  'gom ghiec',
  L10nService().translate('home_kinhtm_c7ed7d'),
  'kinh tom',
  L10nService().translate('home_bnthu_efe91f'),
  'ban thiu',
  L10nService().translate('home_ddy_2cef5f'),
  'do day',
  L10nService().translate('home_cnb_3e1ddb'),
  'can ba',
  L10nService().translate('home_rcri_d2344f'),
  'rac ruoi',
  L10nService().translate('home_nghitsc_87910f'),
  'nghiet suc',
  L10nService().translate('home_scvt_1b259b'),
  'suc vat',
  L10nService().translate('home_ngdc_3708d0'),
  'dong duc',
  L10nService().translate('home_lnging_6320a1'),
  'len giong',
  L10nService().translate('home_tdo_443c69'),
  'dit dao',
  L10nService().translate('home_chi_36a906'),
  'choi di',
  L10nService().translate('home_ph_dd8089'),
  'pha do',
  L10nService().translate('home_checkhng_14c750'),
  'check hang',
  L10nService().translate('home_rausch_35e489'),
  'rau sach',
  L10nService().translate('home_nngdn_5fd2b0'),
  'nong dan',
  L10nService().translate('home_chnrau_0bf913'),
  'chan rau',
  L10nService().translate('home_chnchui_c816ea'),
  'chan chuoi',
  'sugar baby',
  'sugar daddy',
  L10nService().translate('home_lulu_83bb8f'),
  'leu leu',
  L10nService().translate('home_v_840aa8'),
  'vu',
  L10nService().translate('home_bm_0253fe'),
  'buom',
  'chim',
  L10nService().translate('home_chui_10ff2c'),
  L10nService().translate('home_bm_cada33'),
  'bim',
  'khe',
  L10nService().translate('home_l_445144'),
  L10nService().translate('home_ncln_80d018'),
  'nuoc lon',
  L10nService().translate('home_tinhtrng_edc47e'),
  'tinh trung',
  L10nService().translate('home_xuttinh_3507f4'),
  'xuat tinh',
  L10nService().translate('home_bntinh_8b63ec'),
  'ban tinh',
  L10nService().translate('home_phunnc_b08a7e'),
  'phun nuoc',
  L10nService().translate('home_lnnh_5b22d0'),
  'len dinh',
  L10nService().translate('home_sng_ef5c6c'),
  'suong',
  L10nService().translate('home_rnr_4eadd2'),
  'ren ri',
  L10nService().translate('home_mt_ca12c7'),
  'mut',
  L10nService().translate('home_lim_85d086'),
  'liem',
  L10nService().translate('home_cn_2f8300'),
  'can',
  L10nService().translate('home_co_795fa6'),
  'cao',
  L10nService().translate('home_bp_11ce31'),
  'bop',
  L10nService().translate('home_nn_72f4b7'),
  'nan',
  'xoa',
  'xoa',
  L10nService().translate('home_s_432cd3'),
  'so',
  L10nService().translate('home_mc_c7df7c'),
  'moc',
  L10nService().translate('home_ngoy_96e573'),
  'ngoay',
  L10nService().translate('home_m_9ed2c9'),
  'dam',
  L10nService().translate('home_thc_b59b41'),
  'thoc',
  L10nService().translate('home_rt_30c7a3'),
  'rut',
  L10nService().translate('home_nhp_a1a326'),
  'nhap',
  L10nService().translate('home_gi_72e06e'),
  'gia',
  L10nService().translate('home_nn_0a8a03'),
  'nen',
  'phang',
  'phang',
  L10nService().translate('home_qut_2bf99e'),
  'quat',
  L10nService().translate('home_xoc_b51bc6'),
  'xoac',
  L10nService().translate('home_chch_9d9106'),
  'chich',
  L10nService().translate('home_txt_70b3fa'),
  'du',
  L10nService().translate('home_t_3171fd'),
  'dit',
  L10nService().translate('home_xphnh_c47776'),
  'xep hinh',
  L10nService().translate('home_giaophi_f4003b'),
  'giao phoi',
  L10nService().translate('home_quanh_3b8d2d'),
  'quan he',
  L10nService().translate('home_ngvi_129ca6'),
  'ngu voi',
  L10nService().translate('home_lmtnh_77387a'),
  'lam tinh',
  L10nService().translate('home_ni_a47672'),
  'an ai',
  L10nService().translate('home_myma_87881b'),
  'may mua',
  L10nService().translate('home_phngthe_c838e5'),
  'phong the',
  L10nService().translate('home_chngi_681e0d'),
  'chan goi',
  L10nService().translate('home_dcvng_56986e'),
  'duc vong',
  L10nService().translate('home_hammun_583ebf'),
  'ham muon',
  L10nService().translate('home_kchdc_a67cc9'),
  'kich duc',
  L10nService().translate('home_khugi_6588f7'),
  'kheu goi',
  L10nService().translate('home_gitnh_b29411'),
  'goi tinh',
  L10nService().translate('home_quynr_22314b'),
  'quyen ru',
  'sexy',
  'hot',
  L10nService().translate('home_khoehng_e41ee8'),
  'khoe hang',
  L10nService().translate('home_lhng_cb4841'),
  'lo hang',
  L10nService().translate('home_hhnh_8c5189'),
  'ho henh',
  L10nService().translate('home_thrng_1cd73e'),
  'tha rong',
  L10nService().translate('home_xuynthu_cea90f'),
  'xuyen thau',
  L10nService().translate('home_ltkhe_9ced7c'),
  'lot khe',
  L10nService().translate('home_lt_3b1b1d'),
  'do lot',
  L10nService().translate('home_niy_967e07'),
  'noi y',
  'bikini',
  L10nService().translate('home_bi_dfe9ca'),
  'do boi',
  L10nService().translate('home_tmtin_c9ef57'),
  'tam tien',
  L10nService().translate('home_khothn_a400b9'),
  'khoa than',
  L10nService().translate('home_trntrung_4ea698'),
  'tran truong',
  L10nService().translate('home_nhng_90541b'),
  'nhong',
  L10nService().translate('home_ci_be3aec'),
  'coi do',
  L10nService().translate('home_lt_d43d91'),
  'lot do',
  L10nService().translate('home_xo_6d646d'),
  'xe ao',
  L10nService().translate('home_ttqun_fa31c2'),
  'tut quan',
  L10nService().translate('home_banhhng_ac0015'),
  'banh hang',
  L10nService().translate('home_dngchn_11ba28'),
  'dang chan',
  L10nService().translate('home_chngmng_2e60a1'),
  'chong mong',
  L10nService().translate('home_congt_1d66c9'),
  'cong dit',
  L10nService().translate('home_vnhmng_5a12cf'),
  'venh mong',
  L10nService().translate('home_nngc_667102'),
  'uon nguc',
  L10nService().translate('home_khoev_a4eabe'),
  'khoe vu',
  L10nService().translate('home_khoemng_10926c'),
  'khoe mong',
  L10nService().translate('home_khoebm_ad79ea'),
  'khoe buom',
  'khoe chim',
  'khoe chim',
  L10nService().translate('home_khoecc_a0d963'),
  'khoe cac',
  L10nService().translate('home_sc_d1acf2'),
  'suc',
  L10nService().translate('home_thm_828b7f'),
  'tham',
  'quay',
  'quay',
  L10nService().translate('home_vut_cabbbd'),
  'vuot',
  L10nService().translate('home_bn_24f771'),
  'ban',
  L10nService().translate('home_pht_a220df'),
  'phot',
  L10nService().translate('home_tr_4ade9e'),
  'tro',
  L10nService().translate('home_ph_f8c72e'),
  'phe',
  L10nService().translate('home_t_fce367'),
  'te',
  L10nService().translate('home_m_5836f3'),
  'de me',
  L10nService().translate('home_ngtngy_a094aa'),
  'ngat ngay',
  L10nService().translate('home_sungsng_346115'),
  'sung suong',
  L10nService().translate('home_cckhoi_018454'),
  'cuc khoai',
  L10nService().translate('home_hngphn_e1f3d8'),
  'hung phan',
  L10nService().translate('home_bnlon_4bffc0'),
  'ban loan',
  L10nService().translate('home_phtin_477c00'),
  'phat dien',
  L10nService().translate('home_rorc_e09e25'),
  'rao ruc',
  L10nService().translate('home_btrt_7547bf'),
  'but rut',
  L10nService().translate('home_khchu_4f3aff'),
  'kho chiu',
  L10nService().translate('home_thmkht_49e44e'),
  'them khat',
  L10nService().translate('home_ikht_eddacb'),
  'doi khat',
  L10nService().translate('home_thmmun_e72ca9'),
  'them muon',
  L10nService().translate('home_ngo_cd07ce'),
  'ngao',
  'ngu',
  'ngu',
  L10nService().translate('home_n_4f9fff'),
  'dan',
  L10nService().translate('home_t_179069'),
  'dut',
  L10nService().translate('home_tr_fbff2c'),
  'tri',
  L10nService().translate('home_lc_0b3e11'),
  'lac',
  L10nService().translate('home_tht_015abb'),
  'thot',
  L10nService().translate('home_m_061dec'),
  'mu',
  L10nService().translate('home_cm_ebd5f2'),
  'cam',
  L10nService().translate('home_ic_06d73d'),
  'diec',
  L10nService().translate('home_qu_10f283'),
  'que',
  L10nService().translate('home_ct_760460'),
  'cut',
  L10nService().translate('home_lit_79e6c0'),
  'liet',
  'sida',
  'hiv',
  'giang mai',
  'giang mai',
  L10nService().translate('home_simog_8df78c'),
  'sui mao ga',
  L10nService().translate('home_hclo_8493b6'),
  'hac lao',
  'lang ben',
  'lang ben',
  L10nService().translate('home_ghl_353ed2'),
  'ghe lo',
  L10nService().translate('home_hinch_74dad4'),
  'hoi nach',
  L10nService().translate('home_hichn_b9f751'),
  'hoi chan',
  L10nService().translate('home_himing_6616c8'),
  'hoi mieng',
  L10nService().translate('home_bi_a79b84'),
  'bui',
  L10nService().translate('home_bo_449187'),
  'beo',
  'cay',
  L10nService().translate('home_tcmy_82c83e'),
  'dit cu may',
  L10nService().translate('home_tmmy_e8b783'),
  'dit me may',
  L10nService().translate('home_conln_31375d'),
  'con di lon',
  L10nService().translate('home_thngmtln_7f910a'),
  'thang mat lon',
  L10nService().translate('home_cithscvt_314975'),
  'cai thu suc vat',
  L10nService().translate('home_tbmy_6b15c8'),
  'dit bo may',
  L10nService().translate('home_nhciln_800ec9'),
  'nhu cai lon',
  L10nService().translate('home_nhciubui_b8d303'),
  'nhu cai dau buoi',
  L10nService().translate('home_nhcicc_9afc84'),
  'nhu cai cac',
  L10nService().translate('home_cchvl_a5a927'),
  'oc cho vl',
  L10nService().translate('home_ngunhb_ed5da8'),
  'ngu nhu bo',
  L10nService().translate('home_ngunhln_b0c443'),
  'ngu nhu lon',
  L10nService().translate('home_ctmmyi_8e9b60'),
  'cut me may di',
  L10nService().translate('home_binmmyi_339235'),
  'bien me may di',
  L10nService().translate('home_chtmmyi_7d270b'),
  'chet me may di',
  L10nService().translate('home_chtcmyi_8f0e75'),
  'chet cu may di',
  L10nService().translate('home_bnichamy_da01df'),
  'ba noi cha may',
  L10nService().translate('home_tchamy_1c6058'),
  'to cha may',
  L10nService().translate('home_mmy_31c9fa'),
  'du ma may',
  L10nService().translate('home_mmy_9a36c2'),
  'du di me may',
  L10nService().translate('home_nga_accf97'),
  'di ngua',
  L10nService().translate('home_imthi_f792a9'),
  'di diem thui',
  L10nService().translate('home_phnt_b92795'),
  'pho nat',
  L10nService().translate('home_hngdt_59d61d'),
  'hang dat',
  've chai',
  've chai',
  L10nService().translate('home_ngnt_889ea5'),
  'dong nat',
  L10nService().translate('home_rcrixhi_d90423'),
  'rac ruoi xa hoi',
  L10nService().translate('home_cnbxhi_8d7427'),
  'can ba xa hoi',
  L10nService().translate('home_ksinhtrng_0b13a8'),
  'ky sinh trung',
  L10nService().translate('home_bmvym_ec0ee5'),
  'bam vay me',
  L10nService().translate('home_nbm_7fe8a7'),
  'an bam',
  L10nService().translate('home_vtchs_c7e809'),
  'vo tich su',
  L10nService().translate('home_bi_974e77'),
  'do bo di',
  L10nService().translate('home_phvt_45e693'),
  'phe vat',
  L10nService().translate('home_vdng_36d569'),
  'vo dung',
  L10nService().translate('home_btti_41d748'),
  'bat tai',
  L10nService().translate('home_kmci_5a7f5f'),
  'kem coi',
  L10nService().translate('home_hnh_2860fe'),
  'hen ha',
  L10nService().translate('home_nhcnh_e625b1'),
  'nhuc nha',
  L10nService().translate('home_xuh_fff5ea'),
  'xau ho',
  L10nService().translate('home_mtmt_037a16'),
  'mat mat',
  L10nService().translate('home_mtdy_a6e71a'),
  'mat day',
  L10nService().translate('home_hnlo_babc1e'),
  'hon lao',
  L10nService().translate('home_hnxc_b0ac68'),
  'hon xuoc',
  L10nService().translate('home_vhc_77d16a'),
  'vo hoc',
  L10nService().translate('home_thiugiodc_4c2b4b'),
  'thieu giao duc'
];
