part of '../community_tab.dart';

const int _communityPostMaxLength = 300;
const int _communityCommentMaxLength = 180;
const int _communitySearchHistoryLimit = 10;
const String _communitySearchHistoryPrefsKey = 'community_search_history_v1';
const String _communityHiddenPostsPrefsKey = 'community_hidden_posts_v1';
const String _communityAnniversaryMemoryShownPrefsKey =
    'community_anniversary_memory_shown_v1';
const String _communityMessengerButtonOffsetXPrefsKey =
    'community_messenger_button_offset_x_v1';
const String _communityMessengerButtonOffsetYPrefsKey =
    'community_messenger_button_offset_y_v1';
const bool _communityClosedUntilNextVersion = false;
// Toggle this flag when you want to quickly hide/show the community feed modules.
const bool _communityPreviewModeEnabled = false;
const Set<String> _communityPreviewFeedTypes = <String>{
  'foryou',
  'locket',
  'global',
  'friends',
  'hot',
};
bool _isCommunityPreviewFeed(String value) =>
    _communityPreviewModeEnabled && _communityPreviewFeedTypes.contains(value);
final DateFormat _kCommunityPostDateFormat = DateFormat('dd/MM/yyyy HH:mm');
const List<String> _communityGuidelinesVi = <String>[
  'Giữ lời lẽ văn minh, không công kích hay quấy rối.',
  'Không đăng nội dung 18+, lừa đảo, spam hoặc gây hại.',
  'Không công khai dữ liệu riêng tư của người khác.',
];
const List<String> _communityGuidelinesEn = <String>[
  'Keep the tone respectful. No harassment or personal attacks.',
  'Do not post 18+, scam, spam, or harmful content.',
  'Do not expose anyone else\'s private information.',
];

bool _communityIsEnglish() => L10nService().locale.languageCode == 'en';

String _ct(String vi, String en) => _communityIsEnglish() ? en : vi;

String _ctf(
  String vi,
  String en, [
  Map<String, Object?> params = const {},
]) {
  var value = _ct(vi, en);
  params.forEach((name, replacement) {
    value = value.replaceAll('{$name}', '${replacement ?? ''}');
  });
  return value;
}

String _communityActionErrorMessage(
  dynamic error, {
  required String viFallback,
  required String enFallback,
}) {
  final info = AppErrorMapper.resolve(
    error,
    fallbackMessage: _ct(viFallback, enFallback),
  );
  final message = info.message.trim();
  final normalized = message.toLowerCase();

  if (normalized.contains('permission-denied') ||
      normalized.contains('không có quyền') ||
      normalized.contains('khong co quyen') ||
      normalized.contains('permission')) {
    return _ct(
      'Máy chủ đang chặn thao tác này. Thường là do nhà hiện tại không còn hợp lệ, tài khoản bị chặn khỏi cộng đồng, hoặc cộng đồng đang ở chế độ giới hạn.',
      'The server is blocking this action. This is usually caused by an invalid active house, a community block on the account, or community restrictions on the server.',
    );
  }

  return message.isEmpty ? _ct(viFallback, enFallback) : message;
}

List<String> _communityGuidelines() =>
    _communityIsEnglish() ? _communityGuidelinesEn : _communityGuidelinesVi;
List<String> _blockedCommunityTerms = <String>[
  '18+',
  'khieu dam',
  'sex',
  'clip nong',
  'nude',
  'au dam',
  'child porn',
  'csam',
  'hiep dam',
  'rape',
  'dit',
  'địt',
  'lon',
  'lồn',
  'cac',
  'cặc',
  'buoi',
  'buồi',
  'cc',
  'cl',
  'vcl',
  'dcm',
  'đcm',
  'vkl',
  'vl',
  'loz',
  'đm',
  'dm',
  'đĩ',
  'di',
  'cave',
  'phò',
  'pho',
  'chịch',
  'chich',
  'nứng',
  'nung',
  'dâm',
  'dam',
  'thu dam',
  'thủ dâm',
  'quay tay',
  'mbbg',
  'sgbb',
  'sgdd',
  'chửi',
  'chui thề',
  'chửi thề',
  'địt mẹ',
  'dit me',
  'con đĩ',
  'con di',
  'thằng chó',
  'thang cho',
  'cức',
  'cứt',
  'đụ',
  'đụ má',
  'đụ mẹ',
  'du ma',
  'du me',
  'củ lồn',
  'cu lon',
  'mặt lồn',
  'mat lon',
  'hãm lồn',
  'ham lon',
  'vãi lồn',
  'vai lon',
  'cái lồn',
  'cai lon',
  'cặc chó',
  'cac cho',
  'ngu như chó',
  'ngu nhu cho',
  'óc chó',
  'oc cho',
  'đầu bò',
  'dau bo',
  'bú cu',
  'bu cu',
  'sục cặc',
  'suc cac',
  'thẩm du',
  'tham du',
  'nứng lồn',
  'nung lon',
  'nứng cặc',
  'nung cac',
  'dâm đãng',
  'dam dang',
  'đĩ điếm',
  'di diem',
  'điếm thúi',
  'diem thui',
  'chó đẻ',
  'cho de',
  'chết tiệt',
  'chet tiet',
  'khốn nạn',
  'khon nan',
  'mất dạy',
  'mat day',
  'vô giáo dục',
  'vo giao duc',
  'đĩ chó',
  'di cho',
  'phò phạch',
  'pho phach',
  'lồn mẹ mày',
  'lon me may',
  'cặc tao',
  'cac tao',
  'địt cụ',
  'dit cu',
  'địt bà',
  'dit ba',
  'địt cha',
  'dit cha',
  'địt con mẹ',
  'dit con me',
  'đmm',
  'dmm',
  'đkm',
  'dkm',
  'vcc',
  'vãi cả cặc',
  'vai ca cac',
  'đéo',
  'deo',
  'bitch',
  'fuck',
  'shit',
  'asshole',
  'cunt',
  'dick',
  'pussy',
  'whore',
  'slut',
  'motherfucker',
  'bastard',
  'suck',
  'blowjob',
  'handjob',
  'tits',
  'boobs',
  'vagina',
  'penis',
  'chịch xã giao',
  'chich xa giao',
  'some',
  'swing',
  'ons',
  'fnb',
  'fwb',
  '4`',
  'đ!',
  'd!',
  'l*n',
  'c*c',
  'b**i',
  'đ*t',
  'vkl',
  'vl',
  'v l',
  'v c l',
  'd c m',
  'd k m',
  'ml',
  'mặt lờ',
  'mat lo',
  'hãm tài',
  'ham tai',
  'ngu học',
  'ngu hoc',
  'đần độn',
  'dan don',
  'thiểu năng',
  'thieu nang',
  'bệnh hoạn',
  'benh hoan',
  'biến thái',
  'bien thai',
  'ấu dâm',
  'au dam',
  'hiếp dâm',
  'hiep dam',
  'thông đít',
  'thong dit',
  'chơi lỗ nhị',
  'choi lo nhi',
  'bạo dâm',
  'bao dam',
  'bạo hành',
  'bao hanh',
  'đánh lộn',
  'danh lon',
  'chém nhau',
  'chem nhau',
  'giết người',
  'giet nguoi',
  'tự tử',
  'tu tu',
  'tự sát',
  'tu sat',
  'ma túy',
  'ma tuy',
  'đập đá',
  'dap da',
  'hút cần',
  'hut can',
  'chơi đồ',
  'choi do',
  'phê cần',
  'phe can',
  'kẹo ke',
  'keo ke',
  'hít ke',
  'hit ke',
  'bay lắc',
  'bay lac',
  'mại dâm',
  'mai dam',
  'gái gọi',
  'gai goi',
  'trai bao',
  'trai bao',
  'bán dâm',
  'ban dam',
  'mua dâm',
  'mua dam',
  'môi giới',
  'moi gioi',
  'tú bà',
  'tu ba',
  'tú ông',
  'tu ong',
  'đánh bạc',
  'danh bac',
  'cờ bạc',
  'co bac',
  'cá độ',
  'ca do',
  'tài xỉu',
  'tai xiu',
  'lô đề',
  'lo de',
  'xổ số',
  'xo so',
  'đá gà',
  'da ga',
  'phản động',
  'phan dong',
  'chống phá',
  'chong pha',
  'khủng bố',
  'khung bo',
  'bom mìn',
  'bom min',
  'vũ khí',
  'vu khi',
  'súng đạn',
  'sung dan',
  'dao kiếm',
  'dao kiem',
  'buôn lậu',
  'buon lau',
  'lừa đảo',
  'lua dao',
  'chiếm đoạt',
  'chiem doat',
  'tống tiền',
  'tong tien',
  'bắt cóc',
  'bat coc',
  'móc túi',
  'moc tui',
  'trộm cắp',
  'trom cap',
  'cướp giật',
  'cuop giat',
  'hiếp giết',
  'hiep giet',
  'phân xác',
  'phan xac',
  'máu me',
  'mau me',
  'kinh dị',
  'kinh di',
  'tởm lợm',
  'tom lom',
  'gớm ghiếc',
  'gom ghiec',
  'kinh tởm',
  'kinh tom',
  'bẩn thỉu',
  'ban thiu',
  'dơ dáy',
  'do day',
  'cặn bã',
  'can ba',
  'rác rưởi',
  'rac ruoi',
  'nghiệt súc',
  'nghiet suc',
  'súc vật',
  'suc vat',
  'động dục',
  'dong duc',
  'lên giống',
  'len giong',
  'địt dạo',
  'dit dao',
  'chơi đĩ',
  'choi di',
  'phá đò',
  'pha do',
  'check hàng',
  'check hang',
  'rau sạch',
  'rau sach',
  'nông dân',
  'nong dan',
  'chăn rau',
  'chan rau',
  'chăn chuối',
  'chan chuoi',
  'sugar baby',
  'sugar daddy',
  'lếu lều',
  'leu leu',
  'vú',
  'vu',
  'bướm',
  'buom',
  'chim',
  'chuối',
  'bím',
  'bim',
  'khe',
  'lỗ',
  'nước lồn',
  'nuoc lon',
  'tinh trùng',
  'tinh trung',
  'xuất tinh',
  'xuat tinh',
  'bắn tinh',
  'ban tinh',
  'phun nước',
  'phun nuoc',
  'lên đỉnh',
  'len dinh',
  'sướng',
  'suong',
  'rên rỉ',
  'ren ri',
  'mút',
  'mut',
  'liếm',
  'liem',
  'cắn',
  'can',
  'cào',
  'cao',
  'bóp',
  'bop',
  'nắn',
  'nan',
  'xoa',
  'xoa',
  'sờ',
  'so',
  'móc',
  'moc',
  'ngoáy',
  'ngoay',
  'đâm',
  'dam',
  'thọc',
  'thoc',
  'rút',
  'rut',
  'nhấp',
  'nhap',
  'giã',
  'gia',
  'nện',
  'nen',
  'phang',
  'phang',
  'quất',
  'quat',
  'xoạc',
  'xoac',
  'chịch',
  'chich',
  'đụ',
  'du',
  'địt',
  'dit',
  'xếp hình',
  'xep hinh',
  'giao phối',
  'giao phoi',
  'quan hệ',
  'quan he',
  'ngủ với',
  'ngu voi',
  'làm tình',
  'lam tinh',
  'ân ái',
  'an ai',
  'mây mưa',
  'may mua',
  'phòng the',
  'phong the',
  'chăn gối',
  'chan goi',
  'dục vọng',
  'duc vong',
  'ham muốn',
  'ham muon',
  'kích dục',
  'kich duc',
  'khêu gợi',
  'kheu goi',
  'gợi tình',
  'goi tinh',
  'quyến rũ',
  'quyen ru',
  'sexy',
  'hot',
  'khoe hàng',
  'khoe hang',
  'lộ hàng',
  'lo hang',
  'hớ hênh',
  'ho henh',
  'thả rông',
  'tha rong',
  'xuyên thấu',
  'xuyen thau',
  'lọt khe',
  'lot khe',
  'đồ lót',
  'do lot',
  'nội y',
  'noi y',
  'bikini',
  'đồ bơi',
  'do boi',
  'tắm tiên',
  'tam tien',
  'khoả thân',
  'khoa than',
  'trần truồng',
  'tran truong',
  'nhộng',
  'nhong',
  'cởi đồ',
  'coi do',
  'lột đồ',
  'lot do',
  'xé áo',
  'xe ao',
  'tụt quần',
  'tut quan',
  'banh háng',
  'banh hang',
  'dạng chân',
  'dang chan',
  'chổng mông',
  'chong mong',
  'cong đít',
  'cong dit',
  'vểnh mông',
  'venh mong',
  'ưỡn ngực',
  'uon nguc',
  'khoe vú',
  'khoe vu',
  'khoe mông',
  'khoe mong',
  'khoe bướm',
  'khoe buom',
  'khoe chim',
  'khoe chim',
  'khoe cặc',
  'khoe cac',
  'sục',
  'suc',
  'thẩm',
  'tham',
  'quay',
  'quay',
  'vuốt',
  'vuot',
  'bắn',
  'ban',
  'phọt',
  'phot',
  'trớ',
  'tro',
  'phê',
  'phe',
  'tê',
  'te',
  'đê mê',
  'de me',
  'ngất ngây',
  'ngat ngay',
  'sung sướng',
  'sung suong',
  'cực khoái',
  'cuc khoai',
  'hưng phấn',
  'hung phan',
  'bấn loạn',
  'ban loan',
  'phát điên',
  'phat dien',
  'rạo rực',
  'rao ruc',
  'bứt rứt',
  'but rut',
  'khó chịu',
  'kho chiu',
  'thèm khát',
  'them khat',
  'đói khát',
  'doi khat',
  'thèm muốn',
  'them muon',
  'ngáo',
  'ngao',
  'ngu',
  'ngu',
  'đần',
  'dan',
  'đụt',
  'dut',
  'trĩ',
  'tri',
  'lác',
  'lac',
  'thọt',
  'thot',
  'mù',
  'mu',
  'câm',
  'cam',
  'điếc',
  'diec',
  'què',
  'que',
  'cụt',
  'cut',
  'liệt',
  'liet',
  'sida',
  'hiv',
  'giang mai',
  'giang mai',
  'sùi mào gà',
  'sui mao ga',
  'hắc lào',
  'hac lao',
  'lang ben',
  'lang ben',
  'ghẻ lở',
  'ghe lo',
  'hôi nách',
  'hoi nach',
  'hôi chân',
  'hoi chan',
  'hôi miệng',
  'hoi mieng',
  'bùi',
  'bui',
  'béo',
  'beo',
  'cay',
  'địt cụ mày',
  'dit cu may',
  'địt mẹ mày',
  'dit me may',
  'con đĩ lồn',
  'con di lon',
  'thằng mặt lồn',
  'thang mat lon',
  'cái thứ súc vật',
  'cai thu suc vat',
  'địt bố mày',
  'dit bo may',
  'như cái lồn',
  'nhu cai lon',
  'như cái đầu buồi',
  'nhu cai dau buoi',
  'như cái cặc',
  'nhu cai cac',
  'óc chó vl',
  'oc cho vl',
  'ngu như bò',
  'ngu nhu bo',
  'ngu như lợn',
  'ngu nhu lon',
  'cút mẹ mày đi',
  'cut me may di',
  'biến mẹ mày đi',
  'bien me may di',
  'chết mẹ mày đi',
  'chet me may di',
  'chết cụ mày đi',
  'chet cu may di',
  'bà nội cha mày',
  'ba noi cha may',
  'tổ cha mày',
  'to cha may',
  'đụ má mày',
  'du ma may',
  'đụ đĩ mẹ mày',
  'du di me may',
  'đĩ ngựa',
  'di ngua',
  'đĩ điếm thúi',
  'di diem thui',
  'phò nát',
  'pho nat',
  'hàng dạt',
  'hang dat',
  've chai',
  've chai',
  'đồng nát',
  'dong nat',
  'rác rưởi xã hội',
  'rac ruoi xa hoi',
  'cặn bã xã hội',
  'can ba xa hoi',
  'ký sinh trùng',
  'ky sinh trung',
  'bám váy mẹ',
  'bam vay me',
  'ăn bám',
  'an bam',
  'vô tích sự',
  'vo tich su',
  'đồ bỏ đi',
  'do bo di',
  'phế vật',
  'phe vat',
  'vô dụng',
  'vo dung',
  'bất tài',
  'bat tai',
  'kém cỏi',
  'kem coi',
  'hèn hạ',
  'hen ha',
  'nhục nhã',
  'nhuc nha',
  'xấu hổ',
  'xau ho',
  'mất mặt',
  'mat mat',
  'mất dạy',
  'mat day',
  'hỗn láo',
  'hon lao',
  'hỗn xược',
  'hon xuoc',
  'vô học',
  'vo hoc',
  'thiếu giáo dục',
  'thieu giao duc'
];
